[workspace]
resolver = "2"
members = [ "crates/cli", "crates/engine", "crates/starlight", "crates/jb", "crates/simulator"]

[workspace.package]
version = "0.1.0"
authors = [
    "Alessio Forte <fortealessio@gmail.com>",
]
description = "High Frequency Workflow Engine"
readme = "README.md"
edition = "2024"
license = "" # TODO: add license

[profile.dev]
debug = 1 # less precise locations

[profile.dev.package."*"]
debug = false # no debug symbols for deps
opt-level = 2 # this makes their code smaller too
