[package]
name = "starlight"
version.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum = "0.8.4"
console-subscriber = "0.4.1"
dotenvy = "0.15.7"
engine = { path = "../engine" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["preserve_order"] }
serde_yml = "0.0.12"
simulator = { path = "../simulator" }
tokio = { version = "1.45.0", features = ["rt-multi-thread", "signal", "sync", "tracing"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
